<a href="https://colab.research.google.com/github/Hamza-benAmmar/Sentiment-analysis-/blob/main/Sentiment_analysis_and_emotion_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow_text
!pip install tensorflow_hub
!pip install transformers
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
#from transformers import TFAutoModel, AutoTokenizer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 53.7 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 32.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 18.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 49.2 MB/s eta 0:00:00


In [ ]:
import pandas as pd

data=pd.read_csv('/content/concatenated_data.csv')

In [ ]:
data=data.loc[:,['sentiment','content']]
copy=data.copy()
data['sentiment'].value_counts()

joy         6761
sadness     5797
anger       2709
fear        2373
love        1641
surprise     719
Name: sentiment, dtype: int64

In [ ]:
data.isnull().sum()


sentiment    0
content      0
dtype: int64

In [ ]:
data.duplicated().sum()


1

In [ ]:
data[data['content'].duplicated() == True]

sentiment                                            content
5067        joy  i feel on the verge of tears from weariness i ...
6133       love              i still feel a craving for sweet food
6563      anger  i tend to stop breathing when i m feeling stre...
7623    sadness  i was intensely conscious of how much cash i h...
7685   surprise  im still not sure why reilly feels the need to...
8246       love  i am not amazing or great at photography but i...
9596        joy  ive also made it with both sugar measurements ...
9687        joy  i had to choose the sleek and smoother feel of...
9769    sadness  i often find myself feeling assaulted by a mul...
9786        joy       i feel im being generous with that statement
10117      fear  i feel pretty tortured because i work a job an...
10581       joy                       i feel most passionate about
11273       joy  i was so stubborn and that it took you getting...
11354      love  i write these words i feel sweet baby kicks fr...
11525      fear  i feel a remembrance of the strange by justin ...
11823       joy  i have chose for myself that makes me feel ama...
12441      love                   i still feel completely accepted
12562  surprise                           i feel so weird about it
12892       joy  i cant escape the tears of sadness and just tr...
13236     anger   i feel like a tortured artist when i talk to her
13846       joy  i feel more adventurous willing to take risks ...
13880      love  i feel like i am very passionate about youtube...
14107  surprise                             i feel kind of strange
14314  surprise    i could feel myself hit this strange foggy wall
14634      fear  i feel pretty weird blogging about deodorant b...
14926      fear  i resorted to yesterday the post peak day of i...
15315       joy  i will feel as though i am accepted by as well...
15329       joy  i shy away from songs that talk about how i fe...
15572     anger  i bet taylor swift basks in the knowledge that...
15705       joy  i began to feel accepted by gaia on her own terms
15876     anger  i was sitting in the corner stewing in my own ...
16060      love  i miss our talks our cuddling our kissing and ...
16466       joy        i feel so blessed to be a part of your days
16478      love  i honestly feel at heart we should be faithful...
16603       joy  i have had several new members tell me how com...
17626       joy  i feel completely blessed to be a part of this...
17672      love  i feel that being faithful isnt enough in your...
17993     anger                           i feel so tortured by it
18086       joy  i feel like i am in paradise kissing those swe...
18262       joy  i realized what i am passionate about helping ...
18265      love  i feel so blessed and honored that we get to b...
18353       joy  i could feel his breath on me and smell the sw...
18415       joy  i loved the feeling i got during an amazing sl...
18502     anger  i am feeling stressed and more than a bit anxious
18575      love  i feel not having a generous spirit or a forgi...
18586   sadness  i found myself feeling inhibited and shushing ...
18917       joy  i feel the need to pimp this since raini my be...
18959      love                      i feel cared for and accepted
19026   sadness  i have not conducted a survey but it is quite ...
19275  surprise  i feel so weird and scattered with all wonders...
19826       joy  i don t always feel like i have amazing style ...
19887       joy  i feel like some of you have pains and you can...

In [ ]:
index = data[data['content'].duplicated() == True].index
data.drop(index, axis = 0, inplace = True)
data.reset_index(inplace=True, drop = True)

In [ ]:
data['sentiment'].value_counts()

joy         6739
sadness     5793
anger       2703
fear        2369
love        1630
surprise     714
Name: sentiment, dtype: int64

In [ ]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from textblob import TextBlob
from nltk.stem.porter import PorterStemmer
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
stop_words=stopwords.words("english")
from nltk.stem import WordNetLemmatizer

def lemmatization(text):
    lemmatizer= WordNetLemmatizer()

    text = text.split()

    text=[lemmatizer.lemmatize(y) for y in text]

    return " " .join(text)

def remove_stop_words(text):

    Text=[i for i in str(text).split() if i not in stop_words]
    return " ".join(Text)

def Removing_numbers(text):
    text=''.join([i for i in text if not i.isdigit()])
    return text

def lower_case(text):

    text = text.split()

    text=[y.lower() for y in text]

    return " " .join(text)

def Removing_punctuations(text):
    ## Remove punctuations
    text = re.sub('[%s]' % re.escape("""!"#$%&'()*+,،-./:;<=>؟?@[\]^_`{|}~"""), ' ', text)
    text = text.replace('؛',"", )

    ## remove extra whitespace
    text = re.sub('\s+', ' ', text)
    text =  " ".join(text.split())
    return text.strip()

def Removing_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

def remove_small_sentences(df):
    for i in range(len(df)):
        if len(df.text.iloc[i].split()) < 3:
            df.text.iloc[i] = np.nan

def normalize_text(data):
    data["content"]=data["content"].apply(lambda text : Removing_urls(text))
    data["content"]=data["content"].apply(lambda text : lower_case(text))
    data["content"]=data["content"].apply(lambda text : remove_stop_words(text))
    data["content"]=data["content"].apply(lambda text : Removing_numbers(text))
    data["content"]=data["content"].apply(lambda text : Removing_punctuations(text))
    data["content"]=data["content"].apply(lambda text : lemmatization(text))
    return data

def normalized_sentence(sentence):
    sentence= lower_case(sentence)
    sentence= remove_stop_words(sentence)
    sentence= Removing_numbers(sentence)
    sentence= Removing_punctuations(sentence)
    sentence= Removing_urls(sentence)
    sentence= lemmatization(sentence)
    return sentence

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
data=normalize_text(data)

In [ ]:
data['sentiment'].value_counts()

joy         6739
sadness     5793
anger       2703
fear        2369
love        1630
surprise     714
Name: sentiment, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['sentiment_label']=le.fit_transform(data['sentiment'])
data['sentiment_label'].value_counts()


2    6739
4    5793
0    2703
1    2369
3    1630
5     714
Name: sentiment_label, dtype: int64

In [ ]:
max_length = 0
for sentence in data['content']:
    length = len(sentence.split())
    if length > max_length:
        max_length = length
max_length

35

In [ ]:
data['sentiment_label']

0        4
1        4
2        0
3        3
4        0
        ..
19943    0
19944    0
19945    2
19946    2
19947    1
Name: sentiment_label, Length: 19948, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X=data['content']
y=data['sentiment_label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, stratify=y,random_state=42)

In [ ]:
y_train.value_counts()

2    5728
4    4924
0    2297
1    2014
3    1385
5     607
Name: sentiment_label, dtype: int64

In [ ]:
from tqdm.auto import tqdm
import tensorflow as tf
from transformers import BertTokenizer

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [ ]:
token = tokenizer(
    data['content'].tolist(),
    max_length=35,
    truncation=True,
    padding='max_length',
    add_special_tokens=True,
    return_tensors='tf'
)


In [ ]:
token


{'input_ids': <tf.Tensor: shape=(19948, 35), dtype=int32, numpy=
array([[  101,  2134,  2102, ...,     0,     0,     0],
       [  101,  2175,  3110, ...,     0,     0,     0],
       [  101, 10047,  9775, ...,     0,     0,     0],
       ...,
       [  101,  2514,  6179, ...,     0,     0,     0],
       [  101, 10047,  3110, ...,     0,     0,     0],
       [  101,  2514,  6881, ...,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(19948, 35), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(19948, 35), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=in

In [ ]:
import numpy as np
X_input_ids = np.zeros((len(data), 35))
X_attn_masks = np.zeros((len(data), 35))

In [ ]:
def generate_training_data(df, ids, masks, tokenizer):
    for i, text in tqdm(enumerate(df['content'])):
        tokenized_text = tokenizer.encode_plus(
            text,
            max_length=35,
            truncation=True,
            padding='max_length',
            add_special_tokens=True,
            return_tensors='tf'
        )
        ids[i, :] = tokenized_text.input_ids
        masks[i, :] = tokenized_text.attention_mask
    return ids, masks

In [ ]:
X_input_ids, X_attn_masks = generate_training_data(data, X_input_ids, X_attn_masks, tokenizer)

0it [00:00, ?it/s]

In [ ]:
labels = np.zeros((len(data), 6))
labels.shape

(19948, 6)

In [ ]:
labels[np.arange(len(data)), data['sentiment_label'].values] = 1 # one-hot encoded target tensor

In [ ]:
labels


array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [ ]:

# creating a data pipeline using tensorflow dataset utility, creates batches of data for easy loading...
dataset = tf.data.Dataset.from_tensor_slices((X_input_ids, X_attn_masks, labels))
dataset.take(1) # one sample data

<_TakeDataset element_spec=(TensorSpec(shape=(35,), dtype=tf.float64, name=None), TensorSpec(shape=(35,), dtype=tf.float64, name=None), TensorSpec(shape=(6,), dtype=tf.float64, name=None))>

In [ ]:
def SentimentDatasetMapFunction(input_ids, attn_masks, labels):
    return {
        'input_ids': input_ids,
        'attention_mask': attn_masks
    }, labels

In [ ]:
dataset = dataset.map(SentimentDatasetMapFunction) # converting to required format for tensorflow dataset


In [ ]:
dataset.take(1)


<_TakeDataset element_spec=({'input_ids': TensorSpec(shape=(35,), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(35,), dtype=tf.float64, name=None)}, TensorSpec(shape=(6,), dtype=tf.float64, name=None))>

In [ ]:
dataset = dataset.shuffle(1000).batch(16, drop_remainder=True) # batch size, drop any left out tensor

In [ ]:
dataset.take(1)


<_TakeDataset element_spec=({'input_ids': TensorSpec(shape=(16, 35), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(16, 35), dtype=tf.float64, name=None)}, TensorSpec(shape=(16, 6), dtype=tf.float64, name=None))>

In [ ]:
p = 0.8
train_size = int((len(data))*p)

In [ ]:
train_size


15958

In [ ]:
train_dataset = dataset.take(train_size)
val_dataset = dataset.skip(train_size)


In [ ]:
from transformers import TFBertModel


In [ ]:
model = TFBertModel.from_pretrained('bert-base-uncased') # bert base model with pretrained weights


Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [ ]:

# defining 2 input layers for input_ids and attn_masks
input_ids = tf.keras.layers.Input(shape=(35,), name='input_ids', dtype='int32')
attn_masks = tf.keras.layers.Input(shape=(35,), name='attention_mask', dtype='int32')

bert_embds = model.bert(input_ids, attention_mask=attn_masks)[1] # 0 -> activation layer (3D), 1 -> pooled output layer (2D)
intermediate_layer = tf.keras.layers.Dense(512, activation='relu', name='intermediate_layer')(bert_embds)
output_layer = tf.keras.layers.Dense(6, activation='softmax', name='output_layer')(intermediate_layer) # softmax -> calcs probs of classes

sentiment_model = tf.keras.Model(inputs=[input_ids, attn_masks], outputs=output_layer)
sentiment_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 35)]         0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 35)]         0           []                               
                                                                                                  
 bert (TFBertMainLayer)         TFBaseModelOutputWi  109482240   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 35,                                            

In [ ]:
optim = tf.keras.optimizers.Adam(learning_rate=1e-5)
loss_func = tf.keras.losses.CategoricalCrossentropy()
acc = tf.keras.metrics.CategoricalAccuracy('accuracy')

In [ ]:
sentiment_model.compile(optimizer=optim, loss=loss_func, metrics=[acc])

In [ ]:
hist = sentiment_model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=2,
)

Epoch 1/2
1246/1246 [==============================] - 211s 134ms/step - loss: 0.5049 - accuracy: 0.8146
Epoch 2/2
1246/1246 [==============================] - 150s 121ms/step - loss: 0.1414 - accuracy: 0.9400
